apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hello 
  janus-idp.io/tekton: hello
  backstage.io/kubernetes-id: hello
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hello
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  